import mongoose, { Document, Schema } from "mongoose";

const videoSchema = new Schema({
  title: { type: String, default: '' },
  location: { type: String, default: '' },
  videoUrl: { type: String, default: '' },
  thumbnail: { type: String, default: '' }
}); // _id is auto-generated by Mongoose

const homeVideosSchema = new Schema({
  videos: {
    type: [videoSchema],
    default: []
  }
}, { timestamps: true });

const HomeVideos = mongoose.model("OrganicHomeVideos", homeVideosSchema);
export default HomeVideos;
