import mongoose from "mongoose";
import { connectDB } from "../src/config/db";
import DropdownOption from "../src/models/dropdown/DropdownOption.model";
import { DROPDOWN_LISTS } from "../src/modules/dropdowns/dropdownLists";

/**
 * Seeds every admin-managed website dropdown with the options the forms show today
 * (copied from the website source). Each row is [label, value] or, for dependent
 * lists, [label, value, parentValue]. Safe to re-run: existing options are left alone,
 * so values an admin has edited, re-ordered or switched off are never overwritten.
 *
 *   npm run seed:dropdowns
 */
type Row = [string, string] | [string, string, string];

const OPTIONS: Record<string, Row[]> = {
  "gender": [
    ["Male", "Male"],
    ["Female", "Female"],
    ["Other", "Other"],
  ],
  "yes-no": [
    ["Yes", "Yes"],
    ["No", "No"],
  ],
  "india-states": [
    ["Andaman and Nicobar Islands", "Andaman and Nicobar Islands"],
    ["Andhra Pradesh", "Andhra Pradesh"],
    ["Arunachal Pradesh", "Arunachal Pradesh"],
    ["Assam", "Assam"],
    ["Bihar", "Bihar"],
    ["Chandigarh", "Chandigarh"],
    ["Chhattisgarh", "Chhattisgarh"],
    ["Dadra and Nagar Haveli and Daman and Diu", "Dadra and Nagar Haveli and Daman and Diu"],
    ["Delhi", "Delhi"],
    ["Goa", "Goa"],
    ["Gujarat", "Gujarat"],
    ["Haryana", "Haryana"],
    ["Himachal Pradesh", "Himachal Pradesh"],
    ["Jammu and Kashmir", "Jammu and Kashmir"],
    ["Jharkhand", "Jharkhand"],
    ["Karnataka", "Karnataka"],
    ["Kerala", "Kerala"],
    ["Ladakh", "Ladakh"],
    ["Lakshadweep", "Lakshadweep"],
    ["Madhya Pradesh", "Madhya Pradesh"],
    ["Maharashtra", "Maharashtra"],
    ["Manipur", "Manipur"],
    ["Meghalaya", "Meghalaya"],
    ["Mizoram", "Mizoram"],
    ["Nagaland", "Nagaland"],
    ["Odisha", "Odisha"],
    ["Puducherry", "Puducherry"],
    ["Punjab", "Punjab"],
    ["Rajasthan", "Rajasthan"],
    ["Sikkim", "Sikkim"],
    ["Tamil Nadu", "Tamil Nadu"],
    ["Telangana", "Telangana"],
    ["Tripura", "Tripura"],
    ["Uttar Pradesh", "Uttar Pradesh"],
    ["Uttarakhand", "Uttarakhand"],
    ["West Bengal", "West Bengal"],
  ],
  "expo-edition": [
    ["Bharat Organic Expo 2027", "2027"],
  ],
  "salutation": [
    ["Mr.", "Mr."],
    ["Ms.", "Ms."],
    ["Mrs.", "Mrs."],
    ["Dr.", "Dr."],
  ],
  "social-media-platform": [
    ["Instagram", "Instagram"],
    ["Facebook", "Facebook"],
    ["X (Twitter)", "X"],
    ["LinkedIn", "LinkedIn"],
  ],
  "awards-applicant-type": [
    ["Individual", "Individual"],
    ["Organization", "Organization"],
    ["Startup", "Startup"],
  ],
  "awards-state-country": [
    ["Andhra Pradesh", "Andhra Pradesh"],
    ["Assam", "Assam"],
    ["Bihar", "Bihar"],
    ["Chhattisgarh", "Chhattisgarh"],
    ["Delhi", "Delhi"],
    ["Goa", "Goa"],
    ["Gujarat", "Gujarat"],
    ["Haryana", "Haryana"],
    ["Himachal Pradesh", "Himachal Pradesh"],
    ["Jharkhand", "Jharkhand"],
    ["Karnataka", "Karnataka"],
    ["Kerala", "Kerala"],
    ["Madhya Pradesh", "Madhya Pradesh"],
    ["Maharashtra", "Maharashtra"],
    ["Odisha", "Odisha"],
    ["Punjab", "Punjab"],
    ["Rajasthan", "Rajasthan"],
    ["Tamil Nadu", "Tamil Nadu"],
    ["Telangana", "Telangana"],
    ["Uttar Pradesh", "Uttar Pradesh"],
    ["Uttarakhand", "Uttarakhand"],
    ["West Bengal", "West Bengal"],
    ["Other (India)", "Other (India)"],
    ["International", "International"],
  ],
  "awards-category": [
    ["Best Hospital / Healthcare Institution", "Best Hospital / Healthcare Institution"],
    ["Excellence in Medical Practice", "Excellence in Medical Practice"],
    ["Ayurveda & Natural Healing Leader", "Ayurveda & Natural Healing Leader"],
    ["Wellness & Spa Brand of the Year", "Wellness & Spa Brand of the Year"],
    ["Fitness Innovation Award", "Fitness Innovation Award"],
    ["Nutrition & Organic Excellence", "Nutrition & Organic Excellence"],
    ["Medical Tourism Excellence", "Medical Tourism Excellence"],
    ["Healthcare Startup of the Year", "Healthcare Startup of the Year"],
    ["Women Leadership in Healthcare", "Women Leadership in Healthcare"],
    ["Lifetime Achievement Award", "Lifetime Achievement Award"],
  ],
  "awards-years-experience": [
    ["Less than 1 Year", "Less than 1 Year"],
    ["1 – 3 Years", "1 – 3 Years"],
    ["3 – 5 Years", "3 – 5 Years"],
    ["5 – 10 Years", "5 – 10 Years"],
    ["10 – 15 Years", "10 – 15 Years"],
    ["15+ Years", "15+ Years"],
  ],
  "awards-team-size": [
    ["1 – 10", "1 – 10"],
    ["11 – 50", "11 – 50"],
    ["51 – 200", "51 – 200"],
    ["200+", "200+"],
  ],
  "advisory-industry-sector": [
    ["Agriculture", "agriculture"],
    ["Technology", "technology"],
    ["Retail", "retail"],
  ],
  "advisory-expertise-area": [
    ["Organic Farming", "farming"],
    ["Supply Chain", "supply"],
    ["Policy Making", "policy"],
  ],
  "advisory-relationship": [
    ["Colleague", "colleague"],
    ["Manager", "manager"],
    ["Self", "self"],
  ],
  "careers-current-location": [
    ["Delhi, NCR", "Delhi, NCR"],
    ["Noida", "Noida"],
    ["Gurugram", "Gurugram"],
    ["Ghaziabad", "Ghaziabad"],
    ["Faridabad", "Faridabad"],
    ["Other", "Other"],
  ],
  "sponsorship-category": [
    ["TITLE SPONSOR", "TITLE SPONSOR"],
    ["POWERED BY SPONSOR", "POWERED BY SPONSOR"],
    ["ASSOCIATE SPONSOR", "ASSOCIATE SPONSOR"],
    ["CONFERENCE SPONSOR", "CONFERENCE SPONSOR"],
    ["REGISTRATION SPONSOR", "REGISTRATION SPONSOR"],
    ["LANYARD SPONSOR", "LANYARD SPONSOR"],
    ["ORGANIC ZONE SPONSOR", "ORGANIC ZONE SPONSOR"],
    ["DIGITAL PARTNER", "DIGITAL PARTNER"],
    ["NETWORKING SPONSOR", "NETWORKING SPONSOR"],
    ["INTERNATIONAL SPONSOR", "INTERNATIONAL SPONSOR"],
    ["VIP LOUNGE SPONSOR", "VIP LOUNGE SPONSOR"],
    ["AWARDS SPONSOR", "AWARDS SPONSOR"],
  ],
  "partnership-category": [
    ["Hotel & Stay Partner", "Hotel & Stay"],
    ["Travel Partner", "Travel"],
    ["Stall Design & Fabrication", "Stall Design"],
    ["Logistics Partner", "Logistics"],
    ["Printing & Branding", "Printing"],
    ["Manpower Supply Partner", "Manpower Supply"],
    ["Custom Partnership", "Custom"],
  ],
  "partner-preferred-category": [
    ["Hotel & Stay Partner", "Hotel & Stay Partner"],
    ["Travel Partner", "Travel Partner"],
    ["Logistics Partner", "Logistics Partner"],
    ["Stall Design Partner", "Stall Design Partner"],
    ["Manpower Supply Partner", "Manpower Supply Partner"],
    ["Printing & Branding Partner", "Printing & Branding Partner"],
  ],
  "partner-state": [
    ["Delhi", "Delhi"],
    ["Maharashtra", "Maharashtra"],
    ["Karnataka", "Karnataka"],
    ["Tamil Nadu", "Tamil Nadu"],
    ["Gujarat", "Gujarat"],
    ["Uttar Pradesh", "Uttar Pradesh"],
    ["Haryana", "Haryana"],
    ["Telangana", "Telangana"],
    ["West Bengal", "West Bengal"],
    ["Other", "Other"],
  ],
  "msme-enterprise-type": [
    ["Micro", "Micro"],
    ["Small", "Small"],
    ["Medium", "Medium"],
  ],
  "msme-major-activity": [
    ["Manufacturing", "Manufacturing"],
    ["Services", "Services"],
    ["Trading", "Trading"],
  ],
  "msme-constitution": [
    ["Private Limited Company", "Private Limited Company"],
    ["Proprietorship", "Proprietorship"],
    ["Partnership", "Partnership"],
    ["LLP", "LLP"],
    ["Public Limited Company", "Public Limited Company"],
  ],
  "msme-entrepreneur-category": [
    ["General", "General"],
    ["OBC", "OBC"],
    ["SC/ST", "SC/ST"],
    ["Women", "Women"],
  ],
  "msme-stall-size": [
    ["9 sqm", "9"],
    ["12 sqm", "12"],
    ["15 sqm", "15"],
    ["18 sqm", "18"],
  ],
  "buyer-business-role": [
    ["Distributor / Wholesaler", "Distributor"],
    ["Retailer (Single/Multi Store)", "Retailer"],
    ["Manufacturer / OEM", "Manufacturer"],
    ["Importer / Exporter", "Importer"],
    ["Consultant / Professional", "Consultant"],
  ],
  "buyer-business-type": [
    ["Proprietorship", "Proprietorship"],
    ["Partnership", "Partnership"],
    ["Pvt Ltd", "Pvt Ltd"],
    ["LLP", "LLP"],
  ],
  "buyer-product-category": [
    ["Organic Foods & Beverages", "Organic Foods & Beverages"],
    ["Natural Health Products", "Natural Health Products"],
    ["Ayurveda & Herbal", "Ayurveda & Herbal"],
    ["Cosmetics & Personal Care", "Cosmetics & Personal Care"],
  ],
  "buyer-value-range": [
    ["Below 10 Lakhs", "Below 10 Lakhs"],
    ["10-50 Lakhs", "10-50 Lakhs"],
    ["50 Lakhs - 1 Crore", "50 Lakhs - 1 Crore"],
    ["1-5 Crore", "1-5 Crore"],
    ["5+ Crore", "5+ Crore"],
  ],
  "buyer-business-model": [
    ["B2B", "B2B"],
    ["D2C", "D2C"],
    ["Retail", "Retail"],
    ["Wholesale", "Wholesale"],
  ],
  "buyer-purchase-frequency": [
    ["Weekly", "Weekly"],
    ["Monthly", "Monthly"],
    ["Quarterly", "Quarterly"],
    ["Annually", "Annually"],
  ],
  "buyer-purchase-timeline": [
    ["Immediate", "Immediate"],
    ["1–3 Months", "1–3 Months"],
    ["3–6 Months", "3–6 Months"],
    ["Exploring", "Exploring"],
  ],
  "buyer-decision-role": [
    ["Final Decision Maker", "Final Decision Maker"],
    ["Influencer", "Influencer"],
    ["Research Only", "Research Only"],
  ],
  "buyer-company-size": [
    ["Micro", "Micro"],
    ["Small", "Small"],
    ["Medium", "Medium"],
    ["Large", "Large"],
  ],
  "buyer-meeting-day": [
    ["Day 1", "Day 1"],
    ["Day 2", "Day 2"],
    ["Day 3", "Day 3"],
  ],
  "buyer-time-slot": [
    ["Morning (10AM - 1PM)", "Morning (10AM - 1PM)"],
    ["Afternoon (2PM - 4PM)", "Afternoon (2PM - 4PM)"],
  ],
  "buyer-meeting-count": [
    ["3-5 Meetings", "3-5 Meetings"],
    ["5-10 Meetings", "5-10 Meetings"],
  ],
  "buyer-secondary-category": [
    ["Ayurveda", "Ayurveda"],
    ["Organic", "Organic"],
    ["Wellness", "Wellness"],
    ["Pharma", "Pharma"],
    ["Cosmetics", "Cosmetics"],
  ],
  "buyer-region": [
    ["North India", "North India"],
    ["South India", "South India"],
    ["East India", "East India"],
    ["West India", "West India"],
    ["Pan India", "Pan India"],
    ["Global", "Global"],
  ],
  "buyer-supplier-type": [
    ["Manufacturer", "Manufacturer"],
    ["Exporter", "Exporter"],
    ["MSME", "MSME"],
    ["Startup", "Startup"],
    ["Wholesaler", "Wholesaler"],
  ],
  "buyer-certification": [
    ["ISO", "ISO"],
    ["GMP", "GMP"],
    ["FDA", "FDA"],
    ["AYUSH", "AYUSH"],
    ["Organic", "Organic"],
    ["Others", "Others"],
  ],
  "buyer-meeting-category": [
    ["Health Supplements", "Health Supplements"],
    ["Organic Food", "Organic Food"],
    ["Herbal Cosmetics", "Herbal Cosmetics"],
    ["Ayurvedic Medicines", "Ayurvedic Medicines"],
  ],
  "buyer-exhibitor-type": [
    ["Manufacturers", "Manufacturers"],
    ["Distributors", "Distributors"],
    ["Service Providers", "Service Providers"],
  ],
  "buyer-meeting-objective": [
    ["Product Sourcing", "Product Sourcing"],
    ["Partnership / Collaboration", "Partnership / Collaboration"],
    ["Distribution Opportunities", "Distribution Opportunities"],
    ["Private label / OEM", "Private label / OEM"],
    ["Investment / Business Expansion", "Investment / Business Expansion"],
  ],
  "buyer-preferred-business-type": [
    ["Bulk Purchase", "Bulk Purchase"],
    ["Private label", "Private label"],
    ["Franchise", "Franchise"],
    ["Exclusive Distribution", "Exclusive Distribution"],
  ],
  "visitor-corporate-industry": [
    ["Healthcare", "Healthcare"],
    ["Wellness", "Wellness"],
    ["Ayurveda", "Ayurveda"],
    ["Medical Devices", "Medical Devices"],
    ["Pharmaceuticals", "Pharmaceuticals"],
    ["Hospitality", "Hospitality"],
    ["IT & Tech", "IT & Tech"],
    ["Others", "Others"],
  ],
  "visitor-corporate-company-size": [
    ["1-50 employees", "1-50"],
    ["51-200 employees", "51-200"],
    ["201-500 employees", "201-500"],
    ["500+ employees", "500+"],
  ],
  "visitor-industry": [
    ["AYUSH", "ayush"],
    ["Agriculture & Organic", "agriculture"],
    ["Fitness & Wellness", "fitness"],
    ["Healthcare Services", "healthcare"],
    ["Pharmaceutical", "pharma"],
    ["Others", "others"],
  ],
  "visitor-company-size": [
    ["1-10 Employees", "1-10"],
    ["11-50 Employees", "11-50"],
    ["51-200 Employees", "51-200"],
    ["200+ Employees", "200+"],
  ],
  "visitor-visit-days": [
    ["1 Day", "1 Day"],
    ["2 Days", "2 Days"],
    ["3 Days", "3 Days"],
    ["All Days", "All Days"],
  ],
  "visitor-conference-role": [
    ["Delegate", "delegate"],
    ["Attendee", "attendee"],
    ["Speaker", "speaker"],
    ["Panel Participant", "panel-participant"],
    ["Industry Expert", "industry-expert"],
  ],
  "health-camp-time-slot": [
    ["10:00 AM - 11:00 AM", "10:00 AM - 11:00 AM"],
    ["11:00 AM - 12:00 PM", "11:00 AM - 12:00 PM"],
    ["12:00 PM - 01:00 PM", "12:00 PM - 01:00 PM"],
    ["02:00 PM - 03:00 PM", "02:00 PM - 03:00 PM"],
    ["03:00 PM - 04:00 PM", "03:00 PM - 04:00 PM"],
    ["04:00 PM - 05:00 PM", "04:00 PM - 05:00 PM"],
  ],
  "exhibitor-business-type": [
    ["Private Ltd. Company", "Private Ltd. Company"],
    ["Public Ltd. Company", "Public Ltd. Company"],
    ["Partnership Company", "Partnership Company"],
    ["Limited Liability Partnership (LLP)", "Limited Liability Partnership (LLP)"],
    ["One Person Company", "One Person Company"],
    ["Sole Proprietorship", "Sole Proprietorship"],
    ["Section 8 Company", "Section 8 Company"],
    ["Others", "Others"],
  ],
  "exhibitor-primary-category": [
    ["Medical & Healthcare", "Medical & Healthcare"],
    ["AYUSH & Traditional Medicine", "AYUSH & Traditional Medicine"],
    ["Wellness, Fitness & Lifestyle", "Wellness, Fitness & Lifestyle"],
    ["Nutrition, Organic & Health Foods", "Nutrition, Organic & Health Foods"],
    ["Beauty, Personal Care & Aesthetic Wellness", "Beauty, Personal Care & Aesthetic Wellness"],
    ["Mental Health, Yoga & Spiritual Wellness", "Mental Health, Yoga & Spiritual Wellness"],
    ["Medical Technology, Diagnostics & Devices", "Medical Technology, Diagnostics & Devices"],
    ["Institutions, Government Bodies & Startups", "Institutions, Government Bodies & Startups"],
  ],
  "exhibitor-sub-category": [
    ["Hospitals & Clinics", "Hospitals & Clinics", "Medical & Healthcare"],
    ["Pharmaceuticals", "Pharmaceuticals", "Medical & Healthcare"],
    ["Medical Services", "Medical Services", "Medical & Healthcare"],
    ["Healthcare Consultants", "Healthcare Consultants", "Medical & Healthcare"],
    ["Ayurveda Products", "Ayurveda Products", "AYUSH & Traditional Medicine"],
    ["Herbal Medicines", "Herbal Medicines", "AYUSH & Traditional Medicine"],
    ["Panchakarma & Therapies", "Panchakarma & Therapies", "AYUSH & Traditional Medicine"],
    ["AYUSH Institutions", "AYUSH Institutions", "AYUSH & Traditional Medicine"],
    ["Fitness Equipment", "Fitness Equipment", "Wellness, Fitness & Lifestyle"],
    ["Wellness Centers", "Wellness Centers", "Wellness, Fitness & Lifestyle"],
    ["Lifestyle Products", "Lifestyle Products", "Wellness, Fitness & Lifestyle"],
    ["Preventive Healthcare", "Preventive Healthcare", "Wellness, Fitness & Lifestyle"],
    ["Organic Food Products", "Organic Food Products", "Nutrition, Organic & Health Foods"],
    ["Nutraceuticals", "Nutraceuticals", "Nutrition, Organic & Health Foods"],
    ["Supplements", "Supplements", "Nutrition, Organic & Health Foods"],
    ["Functional Foods", "Functional Foods", "Nutrition, Organic & Health Foods"],
    ["Skincare", "Skincare", "Beauty, Personal Care & Aesthetic Wellness"],
    ["Cosmetics", "Cosmetics", "Beauty, Personal Care & Aesthetic Wellness"],
    ["Herbal Beauty", "Herbal Beauty", "Beauty, Personal Care & Aesthetic Wellness"],
    ["Aesthetic Clinics", "Aesthetic Clinics", "Beauty, Personal Care & Aesthetic Wellness"],
    ["Yoga Institutes", "Yoga Institutes", "Mental Health, Yoga & Spiritual Wellness"],
    ["Meditation Services", "Meditation Services", "Mental Health, Yoga & Spiritual Wellness"],
    ["Mental Health Solutions", "Mental Health Solutions", "Mental Health, Yoga & Spiritual Wellness"],
    ["Spiritual Organizations", "Spiritual Organizations", "Mental Health, Yoga & Spiritual Wellness"],
    ["Diagnostic Equipment", "Diagnostic Equipment", "Medical Technology, Diagnostics & Devices"],
    ["Medical Devices", "Medical Devices", "Medical Technology, Diagnostics & Devices"],
    ["Digital Health / HealthTech", "Digital Health / HealthTech", "Medical Technology, Diagnostics & Devices"],
    ["AI & Software Solutions", "AI & Software Solutions", "Medical Technology, Diagnostics & Devices"],
    ["Government Bodies", "Government Bodies", "Institutions, Government Bodies & Startups"],
    ["Research Institutes", "Research Institutes", "Institutions, Government Bodies & Startups"],
    ["Universities", "Universities", "Institutions, Government Bodies & Startups"],
    ["Startups", "Startups", "Institutions, Government Bodies & Startups"],
  ],
  "exhibitor-nature-of-business": [
    ["Agency", "Agency"],
    ["Aggregator", "Aggregator"],
    ["Association", "Association"],
    ["College", "College"],
    ["Dealer", "Dealer"],
    ["Digital Media", "Digital Media"],
    ["Distributor", "Distributor"],
    ["Electronic Media", "Electronic Media"],
    ["Government Body", "Government Body"],
    ["Institution", "Institution"],
    ["Manufacturer", "Manufacturer"],
    ["NGO", "NGO"],
    ["Print Media", "Print Media"],
    ["Raw material Supplier", "Raw material Supplier"],
    ["Research Organisation", "Research Organisation"],
    ["Retailer", "Retailer"],
    ["Service Provider", "Service Provider"],
    ["University", "University"],
    ["Others", "Others"],
  ],
  "exhibitor-referred-by": [
    ["Direct Website", "Direct Website"],
    ["Email Marketing", "Email Marketing"],
    ["Social Media", "Social Media"],
    ["Search Engine", "Search Engine"],
    ["Telecalling", "Telecalling"],
    ["Referral", "Referral"],
    ["Others", "Others"],
  ],
  "tds-percent": [
    ["0%", "0"],
    ["1%", "1"],
    ["2%", "2"],
  ],
  "exhibitor-stall-type": [
    ["Shell Space", "Shell Space"],
    ["Raw Space", "Raw Space"],
  ],
  "stall-pl-scheme": [
    ["One Side Open", "One Side Open"],
    ["Two Side Open", "Two Side Open"],
    ["Three Side Open", "Three Side Open"],
    ["Four Side Open (Island)", "Four Side Open (Island)"],
  ],
};

async function seed() {
  try {
    await connectDB();
    let inserted = 0;
    let existing = 0;

    for (const [list, rows] of Object.entries(OPTIONS)) {
      if (!DROPDOWN_LISTS[list]) throw new Error(`"${list}" is not in DROPDOWN_LISTS`);
      for (const [order, [label, value, parentValue = ""]] of rows.entries()) {
        const result = await DropdownOption.updateOne(
          { list, parentValue, value },
          { $setOnInsert: { list, label, value, parentValue, order, isActive: true } },
          { upsert: true }
        );
        if (result.upsertedCount) inserted += 1;
        else existing += 1;
      }
    }

    console.log(`Dropdowns seeded: ${Object.keys(OPTIONS).length} lists, ${inserted} options inserted, ${existing} already present`);
    await mongoose.disconnect();
    process.exit(0);
  } catch (err) {
    console.error("Seed error:", err);
    process.exit(1);
  }
}

seed();
