import { z } from "zod";

export const sponsorsAndAttendSchema = z.object({
  body: z.object({
    enabled: z.boolean().or(z.string()).optional(),
    titlePrefix: z.string().optional(),
    titleHighlight: z.string().optional(),
    description: z.string().optional(),
    image: z.string().optional(),
    imageAlt: z.string().optional(),
    buttonLabel: z.string().optional(),
    buttonHref: z.string().optional(),
    feature1Title: z.string().optional(),
    feature1Desc: z.string().optional(),
    feature2Title: z.string().optional(),
    feature2Desc: z.string().optional(),
    feature3Title: z.string().optional(),
    feature3Desc: z.string().optional(),
    feature4Title: z.string().optional(),
    feature4Desc: z.string().optional(),
    feature5Title: z.string().optional(),
    feature5Desc: z.string().optional(),
    feature6Title: z.string().optional(),
    feature6Desc: z.string().optional(),
    keyPoint1: z.string().optional(),
    keyPoint2: z.string().optional(),
    keyPoint3: z.string().optional(),
    keyPoint4: z.string().optional(),
    keyPoint5: z.string().optional(),
    keyPoint6: z.string().optional(),
    keyPoint7: z.string().optional(),
    keyPoint8: z.string().optional(),
    keyPoint9: z.string().optional(),
    keyPoint10: z.string().optional(),
    leftSection: z.any().optional(),
    centerSection: z.any().optional(),
    rightSection: z.any().optional(),
  }),
});

export type SponsorsAndAttendInput = z.infer<typeof sponsorsAndAttendSchema>["body"];
